#server:
#  port: 8080
#eureka:
#  client:
#    register-with-eureka: false
spring:
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#        - id: user
#          uri: http://localhost:8081
#          predicates:
#            - Path=/api/user/**
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888